import json
import os
from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

# Pfade für die Konfigurationsdateien
CONFIG_DIR = "conf"

# Stelle sicher, dass der conf-Ordner existiert
if not os.path.exists(CONFIG_DIR):
    os.makedirs(CONFIG_DIR)

# Globale Variable zum Speichern der Bibliotheksdaten
library_data = {}


def load_library_data():
    """Lädt die Bauteil-Bibliothek aus der library.json."""
    global library_data
    try:
        with open("library.json", "r", encoding="utf-8") as f:
            library_data = json.load(f)
    except FileNotFoundError:
        print("Fehler: library.json nicht gefunden!")
        library_data = {"copperRails": [], "transformers": [], "transformerSheets": []}
    except json.JSONDecodeError:
        print("Fehler: library.json ist keine valide JSON-Datei!")
        library_data = {"copperRails": [], "transformers": [], "transformerSheets": []}


@app.route("/")
def index():
    """Rendert die Startseite."""
    return render_template("index.html")


@app.route("/configurator")
def configurator():
    """Rendert die Konfigurator-Seite."""
    if not library_data:
        load_library_data()
    return render_template("configurator.html", library=library_data)


@app.route("/bauteile")
def bauteile():
    """Rendert die neue Seite für den Bauteil-Editor."""
    if not library_data:
        load_library_data()
    return render_template("bauteile.html", library=library_data)


@app.route("/simulation")
def simulation():
    """Rendert die Simulations-Konfigurationsseite."""
    return render_template("simulation.html")


@app.route("/analysis")
def analysis():
    """Rendert die Analyse-Seite."""
    return render_template("analysis.html")


# --- Routen für Szenarien-Dateiverwaltung ---


@app.route("/scenarios", methods=["GET"])
def get_scenarios():
    """Gibt eine Liste aller gespeicherten Szenario-Dateinamen zurück."""
    try:
        files = [
            f.replace(".json", "")
            for f in os.listdir(CONFIG_DIR)
            if f.endswith(".json")
        ]
        return jsonify(sorted(files))
    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/scenarios/<name>", methods=["GET", "POST", "DELETE"])
def handle_scenario(name):
    """Laden, Speichern und Löschen von Szenarien."""
    safe_name = "".join(c for c in name if c.isalnum() or c in ("-", "_")).rstrip()
    if not safe_name:
        return jsonify({"error": "Ungültiger Szenario-Name"}), 400

    filepath = os.path.join(CONFIG_DIR, f"{safe_name}.json")

    if request.method == "POST":
        try:
            data = request.json
            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=4)
            return jsonify(
                {"message": f"Szenario '{safe_name}' erfolgreich gespeichert."}
            )
        except Exception as e:
            return jsonify({"error": str(e)}), 500

    if request.method == "GET":
        try:
            with open(filepath, "r", encoding="utf-8") as f:
                data = json.load(f)
            return jsonify(data)
        except FileNotFoundError:
            return jsonify({"error": "Szenario nicht gefunden"}), 404
        except Exception as e:
            return jsonify({"error": str(e)}), 500

    if request.method == "DELETE":
        try:
            os.remove(filepath)
            return jsonify({"message": f"Szenario '{safe_name}' erfolgreich gelöscht."})
        except FileNotFoundError:
            return jsonify({"error": "Szenario nicht gefunden"}), 404
        except Exception as e:
            return jsonify({"error": str(e)}), 500

    return jsonify({"error": "Ungültige Methode"}), 405


@app.route("/generate", methods=["POST"])
def generate_simulation_json():
    form_data = request.json
    simulation_config = {
        "description": "Setup generated by Web UI",
        "simulationParams": form_data.get("simulationParams", {}),
        "electricalSystem": form_data.get("electricalSystem", []),
        "assemblies": form_data.get("assemblies", []),
        "standAloneComponents": form_data.get("standAloneComponents", []),
    }
    try:
        with open("simulation.json", "w", encoding="utf-8") as f:
            json.dump(simulation_config, f, indent=2)
        return jsonify({"message": "simulation.json wurde erfolgreich erstellt!"}), 200
    except Exception as e:
        return jsonify({"message": f"Fehler beim Schreiben der Datei: {e}"}), 500


def get_transformer_components(t, pos):
    """Extrahiert sicher die geometrischen Teile eines Wandlers."""
    components = []
    geo = t.get("geometry", {})
    pos_x = pos.get("x", 0)
    pos_y = pos.get("y", 0)

    if geo.get("type") != "Rectangle":
        return []

    def get_dim(key):
        return geo.get(key, 0)

    components.append(
        {
            "type": "rect",
            "x": pos_x - get_dim("outerAirWidth") / 2,
            "y": pos_y - get_dim("outerAirHeight") / 2,
            "width": get_dim("outerAirWidth"),
            "height": get_dim("outerAirHeight"),
            "fill": "#f0f8ff",
            "label": "Outer Air",
        }
    )
    components.append(
        {
            "type": "rect",
            "x": pos_x - get_dim("coreOuterWidth") / 2,
            "y": pos_y - get_dim("coreOuterHeight") / 2,
            "width": get_dim("coreOuterWidth"),
            "height": get_dim("coreOuterHeight"),
            "fill": "#d3d3d3",
            "label": "Steel Core",
        }
    )
    components.append(
        {
            "type": "rect",
            "x": pos_x - get_dim("coreInnerWidth") / 2,
            "y": pos_y - get_dim("coreInnerHeight") / 2,
            "width": get_dim("coreInnerWidth"),
            "height": get_dim("coreInnerHeight"),
            "fill": "#f0f8ff",
            "label": "Inner Air",
        }
    )
    components.append(
        {
            "type": "rect",
            "x": pos_x - get_dim("innerWidth") / 2,
            "y": pos_y - get_dim("innerHeight") / 2,
            "width": get_dim("innerWidth"),
            "height": get_dim("innerHeight"),
            "fill": "#ffffff",
            "label": "Air Gap",
        }
    )
    return components


@app.route("/visualize", methods=["POST"])
def visualize_setup():
    """Erstellt eine detaillierte Datenstruktur für die SVG-Visualisierung."""
    if not library_data:
        load_library_data()

    form_data = request.json
    svg_elements = []

    for asm_data in form_data.get("assemblies", []):
        rail_name = asm_data.get("copperRailName")
        transformer_name = asm_data.get("transformerName")
        pos = asm_data.get("position", {"x": 0, "y": 0})
        transformer = next(
            (
                t
                for t in library_data.get("transformers", [])
                if t.get("name") == transformer_name
            ),
            None,
        )
        if transformer:
            svg_elements.extend(get_transformer_components(transformer, pos))
        rail = next(
            (
                r
                for r in library_data.get("copperRails", [])
                if r.get("name") == rail_name
            ),
            None,
        )
        if rail:
            svg_elements.append(
                {
                    "type": "rect",
                    "x": pos.get("x", 0) - rail.get("width", 0) / 2,
                    "y": pos.get("y", 0) - rail.get("height", 0) / 2,
                    "width": rail.get("width", 0),
                    "height": rail.get("height", 0),
                    "fill": "#b87333",
                    "label": rail_name,
                }
            )

    for comp_data in form_data.get("standAloneComponents", []):
        comp_name = comp_data.get("name")
        pos = comp_data.get("position", {"x": 0, "y": 0})
        sheet = next(
            (
                s
                for s in library_data.get("transformerSheets", [])
                if s.get("name") == comp_name
            ),
            None,
        )
        if sheet:
            svg_elements.append(
                {
                    "type": "rect",
                    "x": pos.get("x", 0) - sheet.get("width", 0) / 2,
                    "y": pos.get("y", 0) - sheet.get("height", 0) / 2,
                    "width": sheet.get("width", 0),
                    "height": sheet.get("height", 0),
                    "fill": "#a9a9a9",
                    "label": comp_name,
                }
            )

    return jsonify(svg_elements)


if __name__ == "__main__":
    load_library_data()
    app.run(port=7070, debug=True)
